### ISSUE TITLE
compiled code not working

### ISSUE THREAD

**Issue by gitterman** [blurpy/transistor-tester#2]
Hi blurpy,
didn't you need to adapt the pins for the LCD and the rotary encoder?
In your adapted config_328.h you do not mention anything on this.
At least from your supplied schematic, the encoder B pin is different to the default of Markus' firmware.
Also, the 7735 seems to be connected differently.

**Comment by blurpy** [comment]
Hi, I have adjusted the configuration for the encoder and the lcd.

See here: https://github.com/blurpy/transistor-tester/commit/e2e808a6cabf67a0e06fa216ab1ddd5512815963

As I write on the page:

> There are 3 configuration files in the firmware that needs to be adjusted. See the file "Clones" (from the firmware tgz) for the basic changes required to build a compatible firmware for the AY-AT. The additional changes I made are documented here.

I did not document the basic changes needed, as they are already documented in the firmware. Do the changes make sense now?
