### ISSUE TITLE
Can you provide precompiled M firmware？

### ISSUE THREAD

**Issue by ws786873** [blurpy/transistor-tester#3]
I read all your articles and finally found that I couldn't handle the software. It seems that I need to compile it under LINUX. I thought the source code could be burned using ARDUINO, but that's not the case. If possible, please provide a pre-compiled firmware, maybe HEX? So I should be able to burn it in Windows. thank you. If it bothers you, please ignore this problem.

**Comment by blurpy** [comment]
Sure, check the firmware folder for v1.42 now. I'm curious if you can get it done from Windows.

**Comment by ws786873** [comment]
I use progisp  upload the hex and eep, The software prompts that the burning is successful. Let me try to run it

**Comment by ws786873** [comment]
> Sure, check the firmware folder for v1.42 now. I'm curious if you can get it done from Windows.

Hi, my tester will display a white screen after power-on, then display V 1.42M, then display a C in the second line of the voltage, and then insert the capacitor to display the wrong value. Each interval takes tens of seconds.I didn't see any calibration prompt or menu. I don't know where the problem is...

**Comment by blurpy** [comment]
Did you flash the correct firmware? I seem to remember something like that when I installed the modified firmware on an unmodified device by mistake.

**Comment by ws786873** [comment]
> Did you flash the correct firmware? I seem to remember something like that when I installed the modified firmware on an unmodified device by mistake.

The problem has been solved. I didn't set the fuse configuration correctly before. It needs to be set manually under the WIN system. Now the speed is normal after starting up, and it seems that it can be used correctly. But I still haven't encountered the calibration prompt. Do you have a manual for M firmware? The hyperlink in your article seems to be invalid

**Comment by blurpy** [comment]
> The problem has been solved. I didn't set the fuse configuration correctly before.

Good to hear.


> Do you have a manual for M firmware? The hyperlink in your article seems to be invalid

Seems it was deleted. I adjusted the link now so it points to before it was deleted.
